# Generated by Django 3.2.16 on 2022-11-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favoritos', '0002_alter_favoritos_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritos',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
