# Generated by Django 3.2.16 on 2022-11-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favoritos', '0003_favoritos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritos',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
