# Generated by Django 3.2.16 on 2022-11-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favoritos', '0004_favoritos_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritos',
            name='valor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
