# Generated by Django 3.2.16 on 2022-11-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favoritos', '0005_auto_20221117_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40, null=True, unique=True),
        ),
    ]
