# Generated by Django 3.2.16 on 2022-11-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favoritos', '0006_alter_favoritos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
