# Generated by Django 3.2.16 on 2022-10-19 16:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fructosa', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('lactosa', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('sorbitol', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('manitol', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('gos', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('fructano', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('gr', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=5000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnail/%Y/%m/%d/')),
                ('fructosaAmarillo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('lactosaAmarillo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('sorbitolAmarillo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('manitolAmarillo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('gosAmarillo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('fructanoAmarillo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('grAmarillo', models.CharField(max_length=50)),
                ('commentAmarillo', models.TextField(max_length=5000)),
                ('fructosaRojo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('lactosaRojo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('sorbitolRojo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('manitolRojo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('gosRojo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('fructanoRojo', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'verde'), ('item_key2', 'amarillo'), ('item_key3', 'rojo')], max_length=50)),
                ('grRojo', models.CharField(max_length=50)),
                ('commentRojo', models.TextField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
