# Generated by Django 3.2.16 on 2022-11-16 14:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ListadoProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado',
            name='fructano',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='fructanoAmarillo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='fructanoRojo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='fructosa',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='fructosaAmarillo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='fructosaRojo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='gos',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='gosAmarillo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='gosRojo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='lactosa',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='lactosaAmarillo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='lactosaRojo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='manitol',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='manitolAmarillo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='manitolRojo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='sorbitol',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='sorbitolAmarillo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listado',
            name='sorbitolRojo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], max_length=50),
        ),
    ]
