# Generated by Django 3.2.16 on 2022-11-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListadoProductos', '0002_auto_20221116_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listado',
            options={'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
    ]
